### ISSUE TITLE
トークン数について

### ISSUE THREAD

**Issue by Michi-123** [tanreinama/Japanese-BPEEncoder_V2#2]
32000トークン(ja-swe32kfix.txt)で、
print(len(enc.swe))
を実行しますと、177612 となりました。
ニューラルネットワークの出力ノード数は 177612 とするべきでしょうか。

また、最後の方の '<|byte0|>' や'<|endoftext|>' は、どのようなトークンでしょうか。

**Comment by Michi-123** [comment]
最大で32000個のトークンですね。

**Comment by tanreinama** [comment]
異なる文字（慶、𢙎、慶など）を同じトークンにする関係でenc.sweの数はトークンのユニーク数と異なります。
len(set(enc.swe.values()))としてみてください。

**Comment by tanreinama** [comment]
<|byte0|>～<|byte255|>はエンコード出来なかった文字を、Unicodeのバイト列そのものとしてエンコードする時に使われる宇トークンです。そのような仕組みがあるため、このエンコーダーにはOut Of Vocabularyが存在しません。
<|endoftext|>は出力の終わりを表します。

**Comment by Michi-123** [comment]
ありがとうございました。
